version: '3.5'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
  
  node:
    depends_on:
      - db
    build: .
    environment:
      DATABASE_URL: mysql://root:root@db:3306/db
    ports:
      - "3333:3333"